### ISSUE TITLE
Front-end: make fetch() to perform GET /users

### ISSUE THREAD

**Issue by blinkenlichten** [gmo88/node-express#12]
### Implement GET /users by using fetch() JS API.
We need such things to be done:
- Add bare minimum index.html with a <script> tag section.
- When loaded in the browser by navigating localhost:8000/index.html, the front-end must issue a new HTTP GET request with URL `/users` to the back-end, print the result into the console.

**Comment by gmo88** [comment]
> ### Implement GET /users by using fetch() JS API.
> We need such things to be done:
> 
> * Add bare minimum index.html with a <script> tag section.
> * When loaded in the browser by navigating localhost:8000/index.html, the front-end must issue a new HTTP GET request with URL `/users` to the back-end, print the result into the console.

If I clear understood, the `HTTP GET request with URL /users` should bу send request to the back-end immediately and simultaneously when browser loaded.
