### ISSUE TITLE
Front-end get and render page by number

### ISSUE THREAD

**Issue by blinkenlichten** [gmo88/node-express#14]
## Part1 : fetch page
The frontend should have a new function for processing user pages:
`function openPage(page_num)`.
That function must execute asynchronous fetch() that will perform GET request like so:
```
GET /pages/{page_num}
```
And receive Array of JSON objects with user info like name and surname.

## Part2 : render a table
then() callback of the fetching function will modify main page to have a table that will display the contents of the page like so:

```
page: 17
-------------------------
id     | name | surname |
-------------------------
19    | Vasia | Pupenko |
20    | Nina  | Rudenko |
...
```

**Comment by gmo88** [comment]
done
