### ISSUE TITLE
post/put/delete methods implemented before GET is done

### ISSUE THREAD

**Issue by blinkenlichten** [gmo88/node-express#3]
Hey!
All the stuff below this line https://github.com/gmo88/node-express/blob/feature/routers/routers/users.js#L20

is pointless and shouldn't be there, because the GET routers are not ready and you try to implement POST/PUT.
This way, you constrain possible solutions of the original task.

Please, remove those methods, leave only GET.
Then make this JSON thing 
https://github.com/gmo88/node-express/blob/feature/routers/routers/users.js#L4

look like what has been requested:
```
[{"page_id":0, "users": [{"id":0, "name": "Vasia", "surname": "Petevich"}, {"id":1, "name": "Linda", "surname": "Gondor"},.....],
....
{"page_id":13, "users": [{"id":117, "name": "Basia", "surname": "Vitevich"}, {"id":118, "name": "Nina", "surname": "Alinina"},.....]
]
```
And proceed with the GET methods later on.

**Comment by gmo88** [comment]
> Hey!
> All the stuff below this line https://github.com/gmo88/node-express/blob/feature/routers/routers/users.js#L20
> 
> is pointless and shouldn't be there, because the GET routers are not ready and you try to implement POST/PUT.
> This way, you constrain possible solutions of the original task.
> 
> Please, remove those methods, leave only GET.
> Then make this JSON thing
> https://github.com/gmo88/node-express/blob/feature/routers/routers/users.js#L4
> 
> look like what has been requested:
> 
> ```
> [{"page_id":0, "users": [{"id":0, "name": "Vasia", "surname": "Petevich"}, {"id":1, "name": "Linda", "surname": "Gondor"},.....],
> ....
> {"page_id":13, "users": [{"id":117, "name": "Basia", "surname": "Vitevich"}, {"id":118, "name": "Nina", "surname": "Alinina"},.....]
> ]
> ```
> 
> And proceed with the GET methods later on.

You mean, should I use JSON representation of https://github.com/gmo88/node-express/blob/feature/routers/routers/users.js#L4 instead of object  and  move it on stand-alone file?

**Comment by blinkenlichten** [comment]
You are free to use any representation you like, it can be a string or whatsoever.
The point is that there must be no extra methods & clutter before your data model is not ready.
Why is there PUT/POST/DELETE? They were not requested and clutter your code, the bare minimum requirements ask only for the hardcoded data & 2 GET methods.

Please, start with the correct hard coded data set, make it in a way you like and 1 empty GET method.
Commit the result and close this issue.
Then we'll proceed to the correct GET method implementation.

**Comment by gmo88** [comment]
Done :)
