### ISSUE TITLE
implement GET /pages/{page_num} router

### ISSUE THREAD

**Issue by blinkenlichten** [gmo88/node-express#4]
## Task
Implement a router to get the whole page by index, the index starts from 0.
When the index is out of range, the GET method should return 404 with "out of range" error message.

Example:
GET /pages/7 (where 7 is the page_index)

Should return  JSON array object [{"id": 0, "name":"julia", "surname":"roberts"}, ...],
e.g. the users listed on that page.

## Results: Make this a pull-request for branch `feature/routers`

Details about the "git-flow", how to make the pull request on this issue:

update your local branch

```
git checkout feature/routers
git pull origin feature/routers
```
create new branch for the issue ticket

```
git checkout -b feature/issue-4-get-pages
```

hack some code to accomplish the task, then add the files and commit
```
git add <files you changed>
git commit -m "What I have done ... "
```
push your changes to the feature branch
```
git push origin feature/issue-4-get-pages
```

Then havigate to the repository and make a new pull request with source branch `feature/issue-4-get-pages` to the destination branch `feature/routers`. Present the pull request to the reviewer.

**Comment by blinkenlichten** [comment]
After the task has been accomplished, you will click the "merge" button on the pull request and the changes will go to the main branch "feature/routers", then there will be a button available to delete the branch "feature/issue-4-get-pages" it's safe to do so (and to clean up) after the changes have been merged into the development branch.

**Comment by blinkenlichten** [comment]
Please, open the PR, if there will be changes needed.

Maybe, I'm wrong and my syntax knowledge is vague,
but isn't it a return of the result from a local arrow-function scope instead of return of the result of the GET method?
https://github.com/gmo88/node-express/blob/feature/routers/routers/users.js#L18
does this code really work on the sample data?

When writing the routers we should always return the value.

Also, here
https://github.com/gmo88/node-express/blob/feature/routers/routers/users.js#L21
we return the string, but the router will actually return code 200 and the string as a result, so the caller can assume it's actually the valid result, presented as a string.

Express has different behavior for returning HTTP error codes, please use one for 404.
A human will recognize there a text with the error, but not the automatic GET API client.

**Comment by gmo88** [comment]
[https://github.com/gmo88/node-express/blob/feature/routers/routers/users.js#L18](url) actually reduce return data but in very strange format like this: 
404 error //page_id: 0
[ //page_id: 1
  { id: 2, name: 'Kate', surname: 'Winslet' },
  { id: 3, name: 'Brandon', surname: 'Walsh' },
  { id: 4, name: 'Mason', surname: 'Card' }
]
404 error //page_id: 2
404 error  //page_id: 3
404 error  //page_id: 4
404 error  //page_id: 5

**Comment by blinkenlichten** [comment]
I think, it's because the code with `let page_num_index = pages.map(i => i.page_id).indexOf(parseInt(req.params.id));` already provides you the position of the object in the array.


I think, the skeleton of the method should look like this:
```
router.get('/:id', (req, res) => {
    // request id
    let page_num_index = pages.map(i => i.page_id).indexOf(parseInt(req.params.id));
    if (page_num_index >= pages.length || page_num_index < 0) {
       // TODO: invoke return with 404 HTTP code form Express functions. Look up the tutorial to see how.
       return 404; //just a pseud-code
    }
    //invoke HTTP 200 code with resulting object
    return pages[page_num_index];
```

reduce() will be used in another task. Here it's not needed.

**Comment by blinkenlichten** [comment]
With reduce() the method's skeleton would look like this:
```
    // request id
    let index = parseInt(req.params.id);
    let result_obj = null;
    pages.reduce((acc, val, idx) => {
        if (val.page_id === index)
            result_obj = val;
    }, []);
   if (result_obj) {
       //invoke HTTP 200 return code with (result_obj) & return
   }
   // invoke HTTP 404 return code with null object return
```
