### ISSUE TITLE
Implement GET /page/{page_idx}?name={user first name}

### ISSUE THREAD

**Issue by blinkenlichten** [gmo88/node-express#6]
## Add new router with ?name={user name} search request.
The API caller wants be able to find the user by name or surname.

## Make a new GET router with a parameter following the `?` character, so that
```GET /users?name=Vasia```

Will return all users with first name "Vasia".

The returned result must be an array of user objects `[{"id":117, "name":"Vasia", "surname":"Petevich"}, ...., {"id":118, "name":"Vasia", "surname":"Herovish"}].`

The router shall return 404 on user name not found.
The router  shall return 500 on non-alphanumeric characters entered as name.

## Make a new GET router with a parameter following the `?` character, so that
```GET /users?surname=Petrenko```

Will return all users with first name "Petrenko" similar to `?name=`, error codes also similar.

**Comment by gmo88** [comment]
Done.

> ## Add new router with ?name={user name} search request.
> The API caller wants be able to find the user by name or surname.
> 
> ## Make a new GET router with a parameter following the `?` character, so that
> `GET /users?name=Vasia`
> 
> Will return all users with first name "Vasia".
> 
> The returned result must be an array of user objects `[{"id":117, "name":"Vasia", "surname":"Petevich"}, ...., {"id":118, "name":"Vasia", "surname":"Herovish"}].`
> 
> The router shall return 404 on user name not found.
> The router shall return 500 on non-alphanumeric characters entered as name.
> 
> ## Make a new GET router with a parameter following the `?` character, so that
> `GET /users?surname=Petrenko`
> 
> Will return all users with first name "Petrenko" similar to `?name=`, error codes also similar.

Done
