### ISSUE TITLE
Add new router GET /user/{user_id}

### ISSUE THREAD

**Issue by blinkenlichten** [gmo88/node-express#7]
### Implement GET /user/user_id router, returns JSON object
Where user_id is a number >= 0
The router returns a user's JSON object like {"id":107, "name":"Alina", "surname":"Balina"}.

If the user's ID is not found, the router shall return 404 with empty JSON object "{}" as a response.

**Comment by gmo88** [comment]
Task is partially done, but I didn't complete condition with display object that over the condition.
